---
- hosts: bastion.jferre.local 
  gather_facts: false
  vars_files:
    - group_vars/satellite_vars.yml 

  tasks:
    - name: Creating a new organization
      redhat.satellite.organization:
        username: "{{ satellite['username'] }}"
        password: "{{ satellite['password'] }}"
        server_url: "{{ satellite['url'] }}"
        name: "{{ organization }}"
        state: present
        validate_certs: false 

    - name: Create location
      redhat.satellite.location:
        username: "{{ satellite['username'] }}"
        password: "{{ satellite['password'] }}"
        server_url: "{{ satellite['url'] }}"
        name: "{{ location }}"
        organizations:
          - "{{ organization }}" 
        state: present
        validate_certs: false

    - name: Create and publish a content view
      block:
        - name: Create new content view
          redhat.satellite.content_view:
            username: "{{ satellite['username'] }}"
            password: "{{ satellite['password'] }}"
            server_url: "{{ satellite['url'] }}"
            name: "{{ content_view }}"
            organization: "Infra"
            validate_certs: false

        - name: Publish content view 
          redhat.satellite.content_view_version:
            username: "{{ satellite['username'] }}"
            password: "{{ satellite['password'] }}"
            server_url: "{{ satellite['url'] }}"
            content_view: "{{ content_view }}"
            organization: "{{ organization }}"
            version: 1.0 
            lifecycle_environments: 
              - "Library"
            validate_certs: false

    - name: Create host collection
      redhat.satellite.host_collection:
        username: "{{ satellite['username'] }}"
        password: "{{ satellite['password'] }}"
        server_url: "{{ satellite['url'] }}"
        name: "{{ host_collection }}"
        organization: "{{ organization }}"
        state: present
        validate_certs: false

    - name: Create activation keys
      redhat.satellite.activation_key:
        username: "{{ satellite['username'] }}"
        password: "{{ satellite['password'] }}"
        server_url: "{{ satellite['url'] }}"
        name: "{{ item }}"
        organization: "{{ organization }}"
        host_collections:
          - "{{ host_collection }}"
        lifecycle_environment: "Library"
        content_view: "{{ content_view }}" 
        validate_certs: false
      loop: "{{ activation_keys }}"
